2023-07-02 09:55:19,480 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-07-02 09:55:19,482 INFO supervisord started with pid 7
2023-07-02 09:55:20,486 INFO spawned: 'nginx' with pid 10
2023-07-02 09:55:20,490 INFO spawned: 'app' with pid 11
2023-07-02 09:55:21,543 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-07-02 09:55:21,543 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[CTRL] POST /setup
[Time: 02.07.23 09:55:23] [Level: info] id: d00c6ff30d1a05be
[Time: 02.07.23 09:55:23] [Level: info] coordinator: False
[Time: 02.07.23 09:55:23] [Level: info] clients: ['d00c6ff30d1a05be', '24f43cac6b5fd188']
[Time: 02.07.23 09:55:23] [Level: info] state: initial
[CLIENT] Parsing parameter file...
[API] /setup parsing parameter file 
[API] /setup config file found ... parsing file: /mnt/input/config.yaml
YAML file does not follow specification: missing key: eigenvalues
Setting default: eigenvalues.tsv
YAML file does not follow specification: missing key: explained_variance
Setting default: eigenvalues.tsv
YAML file does not follow specification: missing key: output delimiter
Setting default: tab
YAML file does not follow specification: missing key: inertia
Setting default: inertia.tsv
YAML file does not follow specification: missing key: global_factor_score
Setting default: global_factor_score.tsv
YAML file does not follow specification: missing key: omic_factor_score
Setting default: omic_factor_score.tsv
YAML file does not follow specification: missing key: projection_matrix
Setting default: projection_matrix.tsv
[API] /setup config file found ... parsing done
[CLIENT] finished parsing parameter file.
[STARTUP] Instantiate SVD
[Time: 02.07.23 09:55:23] [Level: info] transition: init_pca
[Time: 02.07.23 09:55:24] [Level: info] state: init_pca
[STARTUP] Copy configuration and create dir
/mnt/input/hospital_data_bredel_1.csv
TEST: []
[Time: 02.07.23 09:55:24] [Level: info] Traceback (most recent call last):
  File "/app/engine/app.py", line 169, in guarded_run
    self.run()
  File "/app/engine/app.py", line 184, in run
    transition = self.current_state.run()
  File "/app/apps/svd/app.py", line 75, in run
    raise KeyError('No data found. Please ensure that the data file is present and correctly named.')
KeyError: 'No data found. Please ensure that the data file is present and correctly named.'

