2023-07-01 09:45:40,609 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-07-01 09:45:40,612 INFO supervisord started with pid 8
2023-07-01 09:45:41,615 INFO spawned: 'nginx' with pid 11
2023-07-01 09:45:41,618 INFO spawned: 'app' with pid 12
2023-07-01 09:45:42,662 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-07-01 09:45:42,662 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/app/engine/app.py", line 202, in register
    state.register()
  File "/app/apps/svd/app.py", line 551, in register
    self.register_transition('separate_pca', Role.BOTH) 
  File "/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 01.07.23 09:45:43] [Level: fatal] source state share_projections not accessible for participants
2023-07-01 09:45:43,651 INFO exited: app (exit status 1; not expected)
2023-07-01 09:45:44,656 INFO spawned: 'app' with pid 48
2023-07-01 09:45:45,658 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/app/engine/app.py", line 202, in register
    state.register()
  File "/app/apps/svd/app.py", line 551, in register
    self.register_transition('separate_pca', Role.BOTH) 
  File "/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 01.07.23 09:45:46] [Level: fatal] source state share_projections not accessible for participants
2023-07-01 09:45:46,403 INFO exited: app (exit status 1; not expected)
2023-07-01 09:45:47,406 INFO spawned: 'app' with pid 72
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/app/engine/app.py", line 202, in register
    state.register()
  File "/app/apps/svd/app.py", line 551, in register
    self.register_transition('separate_pca', Role.BOTH) 
  File "/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 01.07.23 09:45:48] [Level: fatal] source state share_projections not accessible for participants
2023-07-01 09:45:48,182 INFO exited: app (exit status 1; not expected)
2023-07-01 09:45:49,185 INFO spawned: 'app' with pid 96
2023-07-01 09:45:50,188 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/app/engine/app.py", line 202, in register
    state.register()
  File "/app/apps/svd/app.py", line 551, in register
    self.register_transition('separate_pca', Role.BOTH) 
  File "/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 01.07.23 09:45:50] [Level: fatal] source state share_projections not accessible for participants
2023-07-01 09:45:50,936 INFO exited: app (exit status 1; not expected)
2023-07-01 09:45:51,939 INFO spawned: 'app' with pid 120
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/app/engine/app.py", line 202, in register
    state.register()
  File "/app/apps/svd/app.py", line 551, in register
    self.register_transition('separate_pca', Role.BOTH) 
  File "/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 01.07.23 09:45:52] [Level: fatal] source state share_projections not accessible for participants
2023-07-01 09:45:53,036 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-07-01 09:45:53,037 INFO exited: app (exit status 1; not expected)
2023-07-01 09:45:54,041 INFO spawned: 'app' with pid 144
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/app/engine/app.py", line 202, in register
    state.register()
  File "/app/apps/svd/app.py", line 551, in register
    self.register_transition('separate_pca', Role.BOTH) 
  File "/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 01.07.23 09:45:54] [Level: fatal] source state share_projections not accessible for participants
2023-07-01 09:45:54,701 INFO exited: app (exit status 1; not expected)
2023-07-01 09:45:55,705 INFO spawned: 'app' with pid 168
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/app/engine/app.py", line 202, in register
    state.register()
  File "/app/apps/svd/app.py", line 551, in register
    self.register_transition('separate_pca', Role.BOTH) 
  File "/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 01.07.23 09:45:56] [Level: fatal] source state share_projections not accessible for participants
2023-07-01 09:45:56,620 INFO exited: app (exit status 1; not expected)
2023-07-01 09:45:58,625 INFO spawned: 'app' with pid 192
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/app/engine/app.py", line 202, in register
    state.register()
  File "/app/apps/svd/app.py", line 551, in register
    self.register_transition('separate_pca', Role.BOTH) 
  File "/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 01.07.23 09:45:59] [Level: fatal] source state share_projections not accessible for participants
2023-07-01 09:45:59,662 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-07-01 09:45:59,662 INFO exited: app (exit status 1; not expected)
2023-07-01 09:46:00,665 INFO spawned: 'app' with pid 216
